import type { MemoryValueType } from './types'

export interface MemoryCatalogField {
  key: string
  label: string
  valueType: MemoryValueType
  sensitive?: boolean
}

export interface MemoryCatalogCategory {
  key: string
  label: string
  description: string
  fields: MemoryCatalogField[]
}

export const MEMORY_CATALOG: MemoryCatalogCategory[] = [
  {
    key: 'identity',
    label: 'Identity',
    description: 'Core details about who you are.',
    fields: [
      { key: 'full_name', label: 'Full name', valueType: 'text', sensitive: true },
      { key: 'preferred_name', label: 'Preferred name', valueType: 'text' },
      { key: 'pronouns', label: 'Pronouns', valueType: 'text' },
      { key: 'birth_date', label: 'Birth date', valueType: 'date', sensitive: true },
      { key: 'birthplace', label: 'Birthplace', valueType: 'text', sensitive: true },
      { key: 'gender_identity', label: 'Gender identity', valueType: 'text', sensitive: true },
      { key: 'nationality', label: 'Nationality', valueType: 'list', sensitive: true },
      { key: 'citizenship', label: 'Citizenship', valueType: 'list', sensitive: true },
      { key: 'languages', label: 'Languages', valueType: 'list' },
      { key: 'timezone', label: 'Timezone', valueType: 'text' },
      { key: 'biography', label: 'Short biography', valueType: 'multiline' },
    ],
  },
  {
    key: 'contact',
    label: 'Contact',
    description: 'How and where you can be reached.',
    fields: [
      { key: 'primary_email', label: 'Primary email', valueType: 'text', sensitive: true },
      { key: 'secondary_emails', label: 'Other emails', valueType: 'list', sensitive: true },
      { key: 'mobile_phone', label: 'Mobile phone', valueType: 'text', sensitive: true },
      { key: 'other_phone_numbers', label: 'Other phone numbers', valueType: 'list', sensitive: true },
      { key: 'home_address', label: 'Home address', valueType: 'multiline', sensitive: true },
      { key: 'mailing_address', label: 'Mailing address', valueType: 'multiline', sensitive: true },
      { key: 'city_region', label: 'City and region', valueType: 'text', sensitive: true },
      { key: 'emergency_contact', label: 'Emergency contact', valueType: 'multiline', sensitive: true },
    ],
  },
  {
    key: 'household',
    label: 'Household',
    description: 'Home, family, and living arrangements.',
    fields: [
      { key: 'household_members', label: 'Household members', valueType: 'list', sensitive: true },
      { key: 'partner_name', label: 'Partner or spouse', valueType: 'text', sensitive: true },
      { key: 'children', label: 'Children', valueType: 'list', sensitive: true },
      { key: 'dependents', label: 'Dependents', valueType: 'list', sensitive: true },
      { key: 'living_arrangement', label: 'Living arrangement', valueType: 'text', sensitive: true },
      { key: 'home_ownership', label: 'Home ownership', valueType: 'text', sensitive: true },
      { key: 'household_responsibilities', label: 'Household responsibilities', valueType: 'list' },
      { key: 'household_notes', label: 'Household notes', valueType: 'multiline', sensitive: true },
    ],
  },
  {
    key: 'relationships',
    label: 'Relationships',
    description: 'Important people and social context.',
    fields: [
      { key: 'close_family', label: 'Close family', valueType: 'list', sensitive: true },
      { key: 'close_friends', label: 'Close friends', valueType: 'list', sensitive: true },
      { key: 'colleagues', label: 'Key colleagues', valueType: 'list', sensitive: true },
      { key: 'important_contacts', label: 'Important contacts', valueType: 'list', sensitive: true },
      { key: 'relationship_roles', label: 'Relationship roles', valueType: 'multiline', sensitive: true },
      { key: 'communication_preferences', label: 'Communication preferences', valueType: 'multiline' },
      { key: 'communication_boundaries', label: 'Communication boundaries', valueType: 'multiline', sensitive: true },
      { key: 'social_commitments', label: 'Regular social commitments', valueType: 'list' },
    ],
  },
  {
    key: 'health',
    label: 'Health',
    description: 'Medical, wellness, accessibility, and fitness information.',
    fields: [
      { key: 'allergies', label: 'Allergies', valueType: 'list', sensitive: true },
      { key: 'medications', label: 'Medications', valueType: 'list', sensitive: true },
      { key: 'health_conditions', label: 'Health conditions', valueType: 'list', sensitive: true },
      { key: 'past_procedures', label: 'Past procedures', valueType: 'list', sensitive: true },
      { key: 'clinicians', label: 'Clinicians and care team', valueType: 'list', sensitive: true },
      { key: 'health_insurance', label: 'Health insurance', valueType: 'text', sensitive: true },
      { key: 'blood_type', label: 'Blood type', valueType: 'text', sensitive: true },
      { key: 'accessibility_needs', label: 'Accessibility needs', valueType: 'multiline', sensitive: true },
      { key: 'dietary_medical_needs', label: 'Medical dietary needs', valueType: 'list', sensitive: true },
      { key: 'mental_health_screenings', label: 'Mental health screenings', valueType: 'multiline', sensitive: true },
      { key: 'fitness_baseline', label: 'Fitness baseline', valueType: 'multiline', sensitive: true },
      { key: 'health_goals', label: 'Health goals', valueType: 'list', sensitive: true },
      { key: 'sleep_notes', label: 'Sleep notes', valueType: 'multiline', sensitive: true },
    ],
  },
  {
    key: 'work',
    label: 'Work',
    description: 'Employment, career, skills, and professional context.',
    fields: [
      { key: 'employer', label: 'Employer', valueType: 'text', sensitive: true },
      { key: 'job_title', label: 'Job title', valueType: 'text' },
      { key: 'industry', label: 'Industry', valueType: 'text' },
      { key: 'work_location', label: 'Work location', valueType: 'text', sensitive: true },
      { key: 'manager', label: 'Manager', valueType: 'text', sensitive: true },
      { key: 'work_email', label: 'Work email', valueType: 'text', sensitive: true },
      { key: 'employment_start_date', label: 'Employment start date', valueType: 'date' },
      { key: 'work_schedule', label: 'Work schedule', valueType: 'multiline' },
      { key: 'professional_skills', label: 'Professional skills', valueType: 'list' },
      { key: 'career_history', label: 'Career history', valueType: 'multiline', sensitive: true },
      { key: 'current_projects', label: 'Current work projects', valueType: 'list', sensitive: true },
      { key: 'professional_memberships', label: 'Professional memberships', valueType: 'list' },
    ],
  },
  {
    key: 'education',
    label: 'Education',
    description: 'Education, qualifications, and ongoing learning.',
    fields: [
      { key: 'institutions', label: 'Institutions', valueType: 'list', sensitive: true },
      { key: 'degrees', label: 'Degrees', valueType: 'list' },
      { key: 'fields_of_study', label: 'Fields of study', valueType: 'list' },
      { key: 'graduation_dates', label: 'Graduation dates', valueType: 'list', sensitive: true },
      { key: 'certifications', label: 'Certifications', valueType: 'list' },
      { key: 'current_courses', label: 'Current courses', valueType: 'list' },
      { key: 'learning_goals', label: 'Learning goals', valueType: 'list' },
    ],
  },
  {
    key: 'finances',
    label: 'Finances',
    description: 'Financial preferences and planning, excluding secret account data.',
    fields: [
      { key: 'home_currency', label: 'Home currency', valueType: 'text' },
      { key: 'income_range', label: 'Income range', valueType: 'text', sensitive: true },
      { key: 'monthly_budget', label: 'Monthly budget', valueType: 'text', sensitive: true },
      { key: 'savings_goals', label: 'Savings goals', valueType: 'list', sensitive: true },
      { key: 'debts_summary', label: 'Debt summary', valueType: 'multiline', sensitive: true },
      { key: 'recurring_bills', label: 'Recurring bills', valueType: 'list', sensitive: true },
      { key: 'subscriptions', label: 'Subscriptions', valueType: 'list', sensitive: true },
      { key: 'financial_institutions', label: 'Financial institutions', valueType: 'list', sensitive: true },
      { key: 'investment_preferences', label: 'Investment preferences', valueType: 'multiline', sensitive: true },
      { key: 'financial_notes', label: 'Financial notes', valueType: 'multiline', sensitive: true },
    ],
  },
  {
    key: 'pets',
    label: 'Pets',
    description: 'Pets, care routines, and important animal health details.',
    fields: [
      { key: 'pets', label: 'Pets', valueType: 'list' },
      { key: 'pet_breeds', label: 'Breeds', valueType: 'list' },
      { key: 'veterinarian', label: 'Veterinarian', valueType: 'text', sensitive: true },
      { key: 'pet_medications', label: 'Pet medications', valueType: 'list', sensitive: true },
      { key: 'feeding_routine', label: 'Feeding routine', valueType: 'multiline' },
      { key: 'pet_care_instructions', label: 'Care instructions', valueType: 'multiline' },
      { key: 'pet_important_dates', label: 'Important pet dates', valueType: 'list' },
      { key: 'pet_insurance', label: 'Pet insurance', valueType: 'text', sensitive: true },
    ],
  },
  {
    key: 'preferences',
    label: 'Preferences',
    description: 'Tastes, favorites, dislikes, and personal style.',
    fields: [
      { key: 'favorite_foods', label: 'Favorite foods', valueType: 'list' },
      { key: 'favorite_drinks', label: 'Favorite drinks', valueType: 'list' },
      { key: 'preferred_cuisines', label: 'Preferred cuisines', valueType: 'list' },
      { key: 'food_dislikes', label: 'Food dislikes', valueType: 'list' },
      { key: 'dietary_preferences', label: 'Dietary preferences', valueType: 'list', sensitive: true },
      { key: 'music_preferences', label: 'Music', valueType: 'list' },
      { key: 'books_and_authors', label: 'Books and authors', valueType: 'list' },
      { key: 'movies_and_tv', label: 'Movies and TV', valueType: 'list' },
      { key: 'hobbies', label: 'Hobbies', valueType: 'list' },
      { key: 'favorite_colors', label: 'Favorite colors', valueType: 'list' },
      { key: 'clothing_sizes', label: 'Clothing sizes', valueType: 'multiline', sensitive: true },
      { key: 'preferred_brands', label: 'Preferred brands', valueType: 'list' },
      { key: 'gift_preferences', label: 'Gift preferences', valueType: 'multiline' },
      { key: 'personal_style', label: 'Personal style', valueType: 'multiline' },
    ],
  },
  {
    key: 'routines',
    label: 'Routines',
    description: 'Daily rhythms, habits, and recurring commitments.',
    fields: [
      { key: 'wake_time', label: 'Typical wake time', valueType: 'text' },
      { key: 'sleep_time', label: 'Typical bedtime', valueType: 'text' },
      { key: 'working_hours', label: 'Working hours', valueType: 'text' },
      { key: 'exercise_routine', label: 'Exercise routine', valueType: 'multiline', sensitive: true },
      { key: 'meal_routine', label: 'Meal routine', valueType: 'multiline' },
      { key: 'commute', label: 'Commute', valueType: 'multiline', sensitive: true },
      { key: 'weekly_commitments', label: 'Weekly commitments', valueType: 'list' },
      { key: 'medication_schedule', label: 'Medication schedule', valueType: 'multiline', sensitive: true },
      { key: 'morning_routine', label: 'Morning routine', valueType: 'multiline' },
      { key: 'evening_routine', label: 'Evening routine', valueType: 'multiline' },
    ],
  },
  {
    key: 'goals',
    label: 'Goals',
    description: 'Current priorities and future plans.',
    fields: [
      { key: 'active_goals', label: 'Active goals', valueType: 'list' },
      { key: 'short_term_goals', label: 'Short-term goals', valueType: 'list' },
      { key: 'long_term_goals', label: 'Long-term goals', valueType: 'list' },
      { key: 'career_goals', label: 'Career goals', valueType: 'list' },
      { key: 'financial_goals', label: 'Financial goals', valueType: 'list', sensitive: true },
      { key: 'relationship_goals', label: 'Relationship goals', valueType: 'list', sensitive: true },
      { key: 'learning_goals_detail', label: 'Learning goals', valueType: 'list' },
      { key: 'goal_deadlines', label: 'Goal deadlines', valueType: 'list' },
      { key: 'current_obstacles', label: 'Current obstacles', valueType: 'multiline', sensitive: true },
    ],
  },
  {
    key: 'travel',
    label: 'Travel',
    description: 'Travel history, plans, and preferences.',
    fields: [
      { key: 'home_airport', label: 'Home airport', valueType: 'text', sensitive: true },
      { key: 'frequent_destinations', label: 'Frequent destinations', valueType: 'list' },
      { key: 'upcoming_trips', label: 'Upcoming trips', valueType: 'list', sensitive: true },
      { key: 'visited_places', label: 'Visited places', valueType: 'list' },
      { key: 'accommodation_preferences', label: 'Accommodation preferences', valueType: 'list' },
      { key: 'transport_preferences', label: 'Transport preferences', valueType: 'list' },
      { key: 'seat_preference', label: 'Seat preference', valueType: 'text' },
      { key: 'loyalty_programs', label: 'Loyalty programs', valueType: 'list', sensitive: true },
      { key: 'travel_document_expiry', label: 'Travel document expiry', valueType: 'list', sensitive: true },
      { key: 'travel_notes', label: 'Travel notes', valueType: 'multiline', sensitive: true },
    ],
  },
  {
    key: 'technology',
    label: 'Technology',
    description: 'Devices, software, services, and technical preferences.',
    fields: [
      { key: 'devices', label: 'Devices', valueType: 'list' },
      { key: 'operating_systems', label: 'Operating systems', valueType: 'list' },
      { key: 'preferred_apps', label: 'Preferred apps', valueType: 'list' },
      { key: 'online_services', label: 'Online services', valueType: 'list', sensitive: true },
      { key: 'email_provider', label: 'Email provider', valueType: 'text', sensitive: true },
      { key: 'ai_provider', label: 'AI provider', valueType: 'text' },
      { key: 'default_ai_model', label: 'Default AI model', valueType: 'text' },
      { key: 'smart_home_devices', label: 'Smart home devices', valueType: 'list', sensitive: true },
      { key: 'technology_accessibility', label: 'Technology accessibility needs', valueType: 'multiline', sensitive: true },
      { key: 'technical_skills', label: 'Technical skills', valueType: 'list' },
    ],
  },
  {
    key: 'vehicles',
    label: 'Vehicles',
    description: 'Vehicles, maintenance, and related logistics.',
    fields: [
      { key: 'vehicles', label: 'Vehicles', valueType: 'list', sensitive: true },
      { key: 'license_plates', label: 'License plates', valueType: 'list', sensitive: true },
      { key: 'registration_expiry', label: 'Registration expiry', valueType: 'list', sensitive: true },
      { key: 'vehicle_insurance_renewal', label: 'Insurance renewal', valueType: 'list', sensitive: true },
      { key: 'maintenance_schedule', label: 'Maintenance schedule', valueType: 'multiline', sensitive: true },
      { key: 'parking_details', label: 'Parking details', valueType: 'multiline', sensitive: true },
      { key: 'transportation_notes', label: 'Transportation notes', valueType: 'multiline' },
    ],
  },
  {
    key: 'possessions',
    label: 'Possessions',
    description: 'Property, equipment, warranties, and important belongings.',
    fields: [
      { key: 'properties', label: 'Properties', valueType: 'list', sensitive: true },
      { key: 'important_possessions', label: 'Important possessions', valueType: 'list', sensitive: true },
      { key: 'appliances', label: 'Appliances', valueType: 'list' },
      { key: 'warranties', label: 'Warranties', valueType: 'list', sensitive: true },
      { key: 'serial_numbers', label: 'Serial numbers', valueType: 'list', sensitive: true },
      { key: 'storage_locations', label: 'Storage locations', valueType: 'multiline', sensitive: true },
      { key: 'purchase_dates', label: 'Purchase dates', valueType: 'list' },
      { key: 'home_inventory_notes', label: 'Home inventory notes', valueType: 'multiline', sensitive: true },
    ],
  },
  {
    key: 'important-dates',
    label: 'Important Dates',
    description: 'Dates worth remembering and planning around.',
    fields: [
      { key: 'personal_birthdays', label: 'Personal birthdays', valueType: 'list', sensitive: true },
      { key: 'family_birthdays', label: 'Family birthdays', valueType: 'list', sensitive: true },
      { key: 'anniversaries', label: 'Anniversaries', valueType: 'list', sensitive: true },
      { key: 'renewals', label: 'Renewals', valueType: 'list', sensitive: true },
      { key: 'appointments', label: 'Appointments', valueType: 'list', sensitive: true },
      { key: 'deadlines', label: 'Deadlines', valueType: 'list', sensitive: true },
      { key: 'memorial_dates', label: 'Memorial dates', valueType: 'list', sensitive: true },
      { key: 'annual_events', label: 'Annual events', valueType: 'list' },
    ],
  },
  {
    key: 'browser_history',
    label: 'Browser History',
    description: 'Patterns and topics from your web browsing.',
    fields: [
      { key: 'most_visited_sites', label: 'Most visited sites', valueType: 'text', sensitive: true },
      { key: 'frequent_searches', label: 'Frequent search topics', valueType: 'text' },
      { key: 'recent_research_topics', label: 'Recent research topics', valueType: 'text' },
      { key: 'browsing_habits', label: 'Browsing habits and patterns', valueType: 'text' },
    ],
  },
  {
    key: 'youtube_watches',
    label: 'YouTube Watches',
    description: 'What you watch on YouTube.',
    fields: [
      { key: 'frequent_channels', label: 'Frequently watched channels', valueType: 'text', sensitive: true },
      { key: 'watch_topics', label: 'Common watch topics', valueType: 'text' },
      { key: 'watch_duration_patterns', label: 'Watch duration patterns', valueType: 'text' },
    ],
  },
  {
    key: 'amazon_orders',
    label: 'Amazon Orders',
    description: 'Purchasing patterns from Amazon.',
    fields: [
      { key: 'recurring_purchases', label: 'Recurring purchases', valueType: 'text', sensitive: true },
      { key: 'spending_categories', label: 'Spending categories', valueType: 'text' },
      { key: 'recent_purchases', label: 'Recent purchases', valueType: 'text', sensitive: true },
    ],
  },
  {
    key: 'email_threads',
    label: 'Email Threads',
    description: 'Communication patterns from email.',
    fields: [
      { key: 'frequent_correspondents', label: 'Frequent correspondents', valueType: 'text', sensitive: true },
      { key: 'email_patterns', label: 'Email patterns', valueType: 'text' },
      { key: 'recurring_topics', label: 'Recurring email topics', valueType: 'text' },
    ],
  },
  {
    key: 'app_usage',
    label: 'App Usage',
    description: 'How you use applications on your Mac.',
    fields: [
      { key: 'most_used_apps', label: 'Most used apps', valueType: 'text' },
      { key: 'usage_patterns', label: 'Usage patterns', valueType: 'text' },
      { key: 'screen_time_trends', label: 'Screen time trends', valueType: 'text' },
    ],
  },
  {
    key: 'photo_memories',
    label: 'Photo Memories',
    description: 'Locations and people in your photos.',
    fields: [
      { key: 'recent_trips', label: 'Recent trips', valueType: 'text', sensitive: true },
      { key: 'frequent_locations', label: 'Frequent locations', valueType: 'text', sensitive: true },
      { key: 'people_in_photos', label: 'People frequently in photos', valueType: 'text', sensitive: true },
    ],
  },
  {
    key: 'location_history',
    label: 'Location History',
    description: 'Where you go.',
    fields: [
      { key: 'frequent_places', label: 'Frequent places', valueType: 'text', sensitive: true },
      { key: 'travel_patterns', label: 'Travel patterns', valueType: 'text' },
      { key: 'home_location', label: 'Home location', valueType: 'text', sensitive: true },
      { key: 'workplace_location', label: 'Workplace location', valueType: 'text', sensitive: true },
    ],
  },
  {
    key: 'weather_patterns',
    label: 'Weather Patterns',
    description: 'Local climate and correlations.',
    fields: [
      { key: 'local_climate', label: 'Local climate', valueType: 'text' },
      { key: 'seasonal_patterns', label: 'Seasonal patterns', valueType: 'text' },
      { key: 'weather_mood_correlations', label: 'Weather-mood correlations', valueType: 'text' },
    ],
  },
  {
    key: 'subscriptions',
    label: 'Subscriptions',
    description: 'Recurring subscriptions and spend.',
    fields: [
      { key: 'active_subscriptions', label: 'Active subscriptions', valueType: 'text', sensitive: true },
      { key: 'recurring_spend', label: 'Recurring monthly spend', valueType: 'text', sensitive: true },
      { key: 'subscription_changes', label: 'Recent subscription changes', valueType: 'text' },
    ],
  },
]

export const MEMORY_CATEGORY_KEYS = MEMORY_CATALOG.map((category) => category.key)
export const MEMORY_FIELDS = MEMORY_CATALOG.flatMap((category, categoryIndex) =>
  category.fields.map((field, fieldIndex) => ({
    ...field,
    category: category.key,
    sortOrder: categoryIndex * 100 + fieldIndex,
  }))
)
