export const IPC = {
  CONVERSATIONS: {
    LIST: 'conversations:list',
    CREATE: 'conversations:create',
    DELETE: 'conversations:delete',
    RENAME: 'conversations:rename',
    UPDATE_MODEL: 'conversations:update-model',
    UPDATE_EFFORT: 'conversations:update-effort',
    UPDATE_MEMORY_MODE: 'conversations:update-memory-mode',
    UPDATE_CONTEXT: 'conversations:update-context',
    UPDATE_ROLE: 'conversations:update-role',
    UPDATE_SYSTEM_PROMPT: 'conversations:update-system-prompt',
    GET_MESSAGES: 'conversations:get-messages',
    SEARCH: 'conversations:search',
    // Broadcast when the main process changes a conversation row on its own —
    // currently only the generated title, which lands after the send call has
    // already returned.
    UPDATED: 'conversations:updated',
  },
  CHAT: {
    SEND: 'chat:send',
    EDIT_MESSAGE: 'chat:edit-message',
    RETRY_MESSAGE: 'chat:retry-message',
    SET_ACTIVE_BRANCH: 'chat:set-active-branch',
    ABORT: 'chat:abort',
    STREAM_CHUNK: 'chat:stream-chunk',
    STREAM_DONE: 'chat:stream-done',
    STREAM_ERROR: 'chat:stream-error',
    SYSTEM_PROMPT: 'chat:system-prompt',
    PREVIEW_SYSTEM_PROMPT: 'chat:preview-system-prompt',
  },
  SETTINGS: {
    GET: 'settings:get',
    SET: 'settings:set',
    GET_PROVIDER: 'settings:get-provider',
    SET_PROVIDER: 'settings:set-provider',
  },
  MODELS: {
    LIST: 'models:list',
  },
  PRODUCT_SEARCH: {
    SEARCH: 'product-search:search',
    ABORT: 'product-search:abort',
  },
  WEBSEARCH: {
    SEARCH: 'websearch:search',
    ABORT: 'websearch:abort',
  },
  RECALL: {
    SEARCH: 'recall:search',
    ABORT: 'recall:abort',
    CLEAR: 'recall:clear',
    START_CONVERSATION: 'recall:start-conversation',
    OPEN_FILE: 'recall:open-file',
    REVEAL_FILE: 'recall:reveal-file',
    HISTORY: 'recall:history',
    DELETE_HISTORY: 'recall:delete-history',
    CLEAR_HISTORY: 'recall:clear-history',
  },
  MEMORY: {
    LIST: 'memory:list',
    GET: 'memory:get',
    UPDATE: 'memory:update',
    CREATE_FIELD: 'memory:create-field',
    DELETE_FIELD: 'memory:delete-field',
    SUGGESTIONS: 'memory:suggestions',
    EXTRACT: 'memory:extract',
    ABORT: 'memory:abort',
    REVIEW_SUGGESTION: 'memory:review-suggestion',
  },
  PROJECTS: {
    LIST: 'projects:list',
    CREATE: 'projects:create',
    UPDATE: 'projects:update',
    DELETE: 'projects:delete',
    REORDER: 'projects:reorder',
    ADD_FILE: 'projects:add-file',
    REMOVE_FILE: 'projects:remove-file',
    ADD_SOURCE: 'projects:add-source',
    REMOVE_SOURCE: 'projects:remove-source',
    LIST_SOURCES: 'projects:list-sources',
    ANALYZE_PSYCHOLOGY: 'projects:analyze-psychology',
    ANALYZE_HEALTH: 'projects:analyze-health',
    COMPLETE_PSYCHOLOGY_TEST: 'projects:complete-psychology-test',
    RESTORE_DEFAULTS: 'projects:restore-defaults',
  },
  IMPORT_CLAUDE: {
    START: 'import-claude:start',
    ABORT: 'import-claude:abort',
    PROGRESS: 'import-claude:progress',
  },
  HEALTH: {
    INGEST: 'health:ingest',
    INGEST_PROGRESS: 'health:ingest-progress',
    INGEST_ABORT: 'health:abort',
    LIST_RECORDS: 'health:list-records',
    LIST_OBSERVATIONS: 'health:list-observations',
    DELETE_RECORD: 'health:delete-record',
    REFRESH_SUMMARY: 'health:refresh-summary',
    GET_SUMMARY: 'health:get-summary',
    LIVE_STATUS: 'health:live-status',
    LIVE_SYNC: 'health:live-sync',
    LIVE_SYNC_ABORT: 'health:live-sync-abort',
    LIVE_SYNC_PROGRESS: 'health:live-sync-progress',
    SCAN_DIRECTORY: 'health:scan-directory',
  },
  ACTIVITY: {
    INGEST: 'activity:ingest',
    INGEST_PROGRESS: 'activity:ingest-progress',
    INGEST_ABORT: 'activity:abort',
    LIST_RECORDS: 'activity:list-records',
    LIST_EVENTS: 'activity:list-events',
    DELETE_RECORD: 'activity:delete-record',
    REFRESH_SUMMARY: 'activity:refresh-summary',
    ESTIMATE_ANALYSIS: 'activity:estimate-analysis',
    GET_RUN_STATE: 'activity:get-run-state',
    RUN_STATE: 'activity:run-state',
    GET_SUMMARY: 'activity:get-summary',
    LIVE_STATUS: 'activity:live-status',
    LIVE_SYNC: 'activity:live-sync',
    LIVE_SYNC_ABORT: 'activity:live-sync-abort',
    LIVE_SYNC_PROGRESS: 'activity:live-sync-progress',
    GRANT_PERMISSION: 'activity:grant-permission',
    SET_AMAZON_COOKIES: 'activity:set-amazon-cookies',
    CLEAR_AMAZON_COOKIES: 'activity:clear-amazon-cookies',
    SET_LOCATION: 'activity:set-location',
    GET_LOCATION: 'activity:get-location',
    FETCH_CURRENT_LOCATION: 'activity:fetch-current-location',
    SIDECAR_AVAILABLE: 'activity:sidecar-available',
    SCAN_DIRECTORY: 'activity:scan-directory',
    LIST_ACCOUNTS: 'activity:list-accounts',
    UPDATE_ACCOUNT: 'activity:update-account',
    SET_ACCOUNT_CREDENTIAL: 'activity:set-account-credential',
    CLEAR_ACCOUNT_CREDENTIAL: 'activity:clear-account-credential',
    SYNC_ACCOUNT: 'activity:sync-account',
    IMPORT_ACCOUNT_EXPORT: 'activity:import-account-export',
    ADD_ACCOUNT_SOURCE: 'activity:add-account-source',
    REMOVE_ACCOUNT_SOURCE: 'activity:remove-account-source',
    SCAN_ACCOUNT_SOURCES: 'activity:scan-account-sources',
  },
  DOCUMENTS: {
    GENERATE: 'documents:generate',
    GENERATE_ALL: 'documents:generate-all',
    REGENERATE_NODE: 'documents:regenerate-node',
    ABORT: 'documents:abort',
    PAUSE: 'documents:pause',
    GET_STATE: 'documents:get-state',
    STATE: 'documents:state',
    GET_TREE: 'documents:get-tree',
    GET_SUMMARIES: 'documents:get-summaries',
    GET_PROVENANCE: 'documents:get-provenance',
    GET_SOURCE_EXCERPT: 'documents:get-source-excerpt',
    GET_USER_CONTEXT: 'documents:get-user-context',
    REFRESH_USER_CONTEXT: 'documents:refresh-user-context',
    PROGRESS: 'documents:progress',
    ESTIMATE: 'documents:estimate',
    ESTIMATE_ALL: 'documents:estimate-all',
  },
  TIMELINE: {
    LIST: 'timeline:list',
    GET_SUMMARY: 'timeline:get-summary',
    GET_YEARS: 'timeline:get-years',
    REBUILD: 'timeline:rebuild',
    ABORT: 'timeline:abort',
    CREATE_EVENT: 'timeline:create-event',
    DELETE_EVENT: 'timeline:delete-event',
    PROGRESS: 'timeline:progress',
    GET_STATE: 'timeline:get-state',
    STATE: 'timeline:state',
  },
  PEOPLE: {
    LIST: 'people:list',
    GET: 'people:get',
    REBUILD: 'people:rebuild',
    ABORT: 'people:abort',
    PAUSE: 'people:pause',
    PIN: 'people:pin',
    MERGE: 'people:merge',
    IGNORE: 'people:ignore',
    SET_RELATION: 'people:set-relation',
    PROGRESS: 'people:progress',
    GET_STATE: 'people:get-state',
    STATE: 'people:state',
  },
  IDEAS: {
    GET: 'ideas:get',
    REFRESH: 'ideas:refresh',
  },
  PLAY: {
    GET: 'play:get',
    REFRESH: 'play:refresh',
    REACT: 'play:react',
    STOP: 'play:stop',
    GET_STATE: 'play:get-state',
    /** Broadcast to every window: a build is long enough to outlive the tab. */
    STATE: 'play:state',
    SET_PROGRESS: 'play:set-progress',
    ARCHIVE: 'play:archive',
  },
  CONTEXT_VERSIONS: {
    LIST: 'context-versions:list',
    GET: 'context-versions:get',
  },
  ROLES: {
    LIST: 'roles:list',
    GET_SESSION_NOTE: 'roles:get-session-note',
    LIST_SESSION_NOTES: 'roles:list-session-notes',
    GENERATE_SESSION_NOTE: 'roles:generate-session-note',
    DELETE_SESSION_NOTE: 'roles:delete-session-note',
    // Broadcast when a background pass writes a note, so an open Psychology
    // page picks it up without polling.
    SESSION_NOTE_ADDED: 'roles:session-note-added',
  },
  APP: {
    OPEN_EXTERNAL: 'app:open-external',
    OPEN_SOURCE_PATH: 'app:open-source-path',
    GET_USER_INFO: 'app:get-user-info',
    SELECT_DIRECTORY: 'app:select-directory',
    SELECT_FILES: 'app:select-files',
    SELECT_IMAGE: 'app:select-image',
    SELECT_ATTACHMENTS: 'app:select-attachments',
  },
  WORK: {
    SAVE_DOCUMENT: 'work:save-document',
    // The AI bridge. REQUEST is a broadcast main -> renderer; RESPONSE is the
    // renderer answering it, keyed by requestId.
    EDITOR_REQUEST: 'work:editor-request',
    EDITOR_RESPONSE: 'work:editor-response',
    SET_EDITOR_OPEN: 'work:set-editor-open',
    // Asking the app to open the Work tab on a new document. Handled by App,
    // not by the editor frame — the frame does not exist yet at that point.
    OPEN_DOCUMENT: 'work:open-document',
  },
  FS: {
    READ_FILE: 'fs:read-file',
    WRITE_FILE: 'fs:write-file',
    LIST_DIR: 'fs:list-dir',
    STAT: 'fs:stat',
  },
  LIBRARY: {
    // scan
    SCAN: 'library:scan',
    SCAN_ABORT: 'library:scan-abort',
    SCAN_PROGRESS: 'library:scan-progress',
    STATE: 'library:state',
    GET_STATE: 'library:get-state',
    // shelf
    LIST_BOOKS: 'library:list-books',
    GET_BOOK: 'library:get-book',
    DELETE_BOOK: 'library:delete-book',
    // reading
    GET_CHAPTER: 'library:get-chapter',
    GET_RESOURCE: 'library:get-resource',
    SET_READING_STATE: 'library:set-reading-state',
    SET_PROGRESS: 'library:set-progress',
    RECORD_SESSION: 'library:record-session',
    // reading-record snapshot (the only paid thing the Library does)
    ESTIMATE_SNAPSHOT: 'library:estimate-snapshot',
    REFRESH_SNAPSHOT: 'library:refresh-snapshot',
    // annotations
    LIST_ANNOTATION_RUNS: 'library:list-annotation-runs',
    LIST_ANNOTATIONS: 'library:list-annotations',
    ESTIMATE_ANNOTATIONS: 'library:estimate-annotations',
    GENERATE_ANNOTATIONS: 'library:generate-annotations',
    DELETE_ANNOTATION_RUN: 'library:delete-annotation-run',
    CREATE_ANNOTATION: 'library:create-annotation',
    SET_ANNOTATION_PINNED: 'library:set-annotation-pinned',
    DELETE_ANNOTATION: 'library:delete-annotation',
    ABORT_GENERATION: 'library:abort-generation',
    // lessons
    LIST_LESSONS: 'library:list-lessons',
    GET_LESSON: 'library:get-lesson',
    ESTIMATE_LESSON: 'library:estimate-lesson',
    GENERATE_LESSON: 'library:generate-lesson',
    DELETE_LESSON: 'library:delete-lesson',
    RECORD_ATTEMPT: 'library:record-attempt',
    LIST_ATTEMPTS: 'library:list-attempts',
    // discussion handoff
    BUILD_DISCUSSION_PROMPT: 'library:build-discussion-prompt',
    LINK_CONVERSATION: 'library:link-conversation',
    LIST_CONVERSATIONS: 'library:list-conversations',
    // narration
    SPEECH_PROVIDERS: 'library:speech-providers',
    SET_SPEECH_KEY: 'library:set-speech-key',
    CLEAR_SPEECH_KEY: 'library:clear-speech-key',
    LIST_VOICES: 'library:list-voices',
    LIST_NARRATION_MODELS: 'library:list-narration-models',
    ESTIMATE_AUDIOBOOK: 'library:estimate-audiobook',
    GENERATE_AUDIOBOOK: 'library:generate-audiobook',
    GET_AUDIOBOOK: 'library:get-audiobook',
    LIST_AUDIOBOOKS: 'library:list-audiobooks',
    DELETE_AUDIOBOOK: 'library:delete-audiobook',
    AUDIOBOOK_PROGRESS: 'library:audiobook-progress',
    // bulk media over HTTP, for bytes that do not belong in a JSON frame.
    // Remote devices only — see docs/ios-app.md "Bulk media".
    GET_MEDIA_URL: 'library:get-media-url',
    // file organisation
    PLAN_ORGANIZE: 'library:plan-organize',
    APPLY_ORGANIZE: 'library:apply-organize',
  },
  PROVIDER_CREDIT: {
    GET: 'provider-credit:get',
    CLEAR: 'provider-credit:clear',
    STATE: 'provider-credit:state',
  },
  CALL_HISTORY: {
    LIST: 'call-history:list',
    GET: 'call-history:get',
    STATS: 'call-history:stats',
    CLEAR: 'call-history:clear',
  },
  MENU: {
    NEW_CHAT: 'menu:new-chat',
    SETTINGS: 'menu:settings',
  },
  REMOTE: {
    GET_STATUS: 'remote:get-status',
    SET_ENABLED: 'remote:set-enabled',
    CREATE_PAIRING: 'remote:create-pairing',
    CANCEL_PAIRING: 'remote:cancel-pairing',
    LIST_DEVICES: 'remote:list-devices',
    REVOKE_DEVICE: 'remote:revoke-device',
    RENAME_DEVICE: 'remote:rename-device',
    STATUS: 'remote:status',
    // Called by the phone, never by the renderer. `settings:get` carries the
    // provider key and is not remote-callable; this is the redacted subset.
    CLIENT_SETTINGS: 'remote:client-settings',
  },
} as const
