import {
  faAlarmClock,
  faAmbulance,
  faAnchor,
  faAppleWhole,
  faArchive,
  faAsterisk,
  faAtom,
  faAward,
  faBaby,
  faBagShopping,
  faBan,
  faBandage,
  faBarcode,
  faBaseball,
  faBasketball,
  faBath,
  faBeerMugEmpty,
  faBell,
  faBellSlash,
  faBicycle,
  faBitcoinSign,
  faBolt,
  faBomb,
  faBone,
  faBook,
  faBookBookmark,
  faBookmark,
  faBookOpen,
  faBookOpenReader,
  faBottleWater,
  faBowlFood,
  faBowlingBall,
  faBowlRice,
  faBox,
  faBoxesStacked,
  faBoxOpen,
  faBrain,
  faBreadSlice,
  faBridge,
  faBriefcase,
  faBroom,
  faBrush,
  faBug,
  faBuilding,
  faBullhorn,
  faBullseye,
  faBurger,
  faBurst,
  faBus,
  faBusSimple,
  faCake,
  faCakeCandles,
  faCalculator,
  faCalendar,
  faCalendarCheck,
  faCalendarDays,
  faCalendarPlus,
  faCalendarXmark,
  faCamera,
  faCampground,
  faCapsules,
  faCar,
  faCaravan,
  faCarrot,
  faCarSide,
  faCartShopping,
  faCashRegister,
  faCat,
  faCertificate,
  faChampagneGlasses,
  faChargingStation,
  faChartArea,
  faChartBar,
  faChartColumn,
  faChartLine,
  faChartPie,
  faCheck,
  faCheese,
  faChess,
  faChild,
  faCircleCheck,
  faCircleHalfStroke,
  faCircleInfo,
  faCircleMinus,
  faCirclePlus,
  faCircleQuestion,
  faCircleXmark,
  faClapperboard,
  faClipboard,
  faClipboardCheck,
  faClipboardList,
  faClock,
  faClockRotateLeft,
  faCloud,
  faClover,
  faCode,
  faCoins,
  faComment,
  faComments,
  faCompactDisc,
  faCompass,
  faCompassDrafting,
  faComputer,
  faConciergeBell,
  faCookie,
  faCookieBite,
  faCopy,
  faCow,
  faCreditCard,
  faCross,
  faCrow,
  faCrown,
  faCube,
  faCubes,
  faDatabase,
  faDesktop,
  faDharmachakra,
  faDiamond,
  faDiamondTurnRight,
  faDice,
  faDog,
  faDollarSign,
  faDoorClosed,
  faDoorOpen,
  faDove,
  faDrum,
  faDrumstickBite,
  faDumbbell,
  faEarListen,
  faEarthAfrica,
  faEarthAmericas,
  faEarthAsia,
  faEarthEurope,
  faEarthOceania,
  faEgg,
  faEnvelope,
  faEnvelopeOpen,
  faEye,
  faFeather,
  faFeatherPointed,
  faFerry,
  faFile,
  faFileAudio,
  faFileCode,
  faFileContract,
  faFileCsv,
  faFileExcel,
  faFileLines,
  faFileMedical,
  faFilePdf,
  faFilePrescription,
  faFileSignature,
  faFileVideo,
  faFileWord,
  faFileZipper,
  faFillDrip,
  faFilm,
  faFingerprint,
  faFire,
  faFish,
  faFlag,
  faFlagCheckered,
  faFlask,
  faFlaskVial,
  faFolder,
  faFolderClosed,
  faFolderMinus,
  faFolderOpen,
  faFolderPlus,
  faFolderTree,
  faFootball,
  faFrog,
  faFutbol,
  faGamepad,
  faGasPump,
  faGear,
  faGears,
  faGem,
  faGhost,
  faGift,
  faGifts,
  faGlassCheers,
  faGlassMartini,
  faGlassWater,
  faGlobe,
  faGuitar,
  faHammer,
  faHamsa,
  faHand,
  faHandBackFist,
  faHandFist,
  faHandHoldingDollar,
  faHandHoldingHeart,
  faHandHoldingMedical,
  faHands,
  faHandshake,
  faHandsPraying,
  faHatCowboy,
  faHatCowboySide,
  faHatWizard,
  faHeadphones,
  faHeadset,
  faHeart,
  faHeartCrack,
  faHeartPulse,
  faHelicopter,
  faHelmetSafety,
  faHippo,
  faHockeyPuck,
  faHorse,
  faHorseHead,
  faHospital,
  faHotdog,
  faHotel,
  faHotTubPerson,
  faHourglass,
  faHourglassHalf,
  faHouse,
  faHouseChimney,
  faIceCream,
  faIndustry,
  faJar,
  faKey,
  faKeyboard,
  faKhanda,
  faKitMedical,
  faKiwiBird,
  faLandmark,
  faLaptop,
  faLaptopCode,
  faLeaf,
  faLemon,
  faLightbulb,
  faLink,
  faLinkSlash,
  faLocationCrosshairs,
  faLocationDot,
  faLock,
  faLockOpen,
  faLuggageCart,
  faMagnifyingGlass,
  faMagnifyingGlassChart,
  faMagnifyingGlassMinus,
  faMagnifyingGlassPlus,
  faMap,
  faMapLocationDot,
  faMartiniGlass,
  faMask,
  faMasksTheater,
  faMedal,
  faMicrochip,
  faMicrophone,
  faMicrophoneLines,
  faMicroscope,
  faMinus,
  faMobile,
  faMobileScreen,
  faMoneyBill,
  faMoneyBillWave,
  faMoneyCheck,
  faMoon,
  faMotorcycle,
  faMountain,
  faMountainSun,
  faMouse,
  faMugHot,
  faMugSaucer,
  faMusic,
  faNetworkWired,
  faNewspaper,
  faNoteSticky,
  faOtter,
  faPaintbrush,
  faPalette,
  faPaperclip,
  faPaperPlane,
  faPassport,
  faPaste,
  faPaw,
  faPen,
  faPencil,
  faPenFancy,
  faPenNib,
  faPeopleGroup,
  faPeopleLine,
  faPepperHot,
  faPercent,
  faPerson,
  faPersonBiking,
  faPersonDress,
  faPersonHiking,
  faPersonPraying,
  faPersonPregnant,
  faPersonRunning,
  faPersonSkating,
  faPersonSkiing,
  faPersonSnowboarding,
  faPersonSwimming,
  faPersonWalking,
  faPhone,
  faPhoneVolume,
  faPiggyBank,
  faPills,
  faPizzaSlice,
  faPlaceOfWorship,
  faPlane,
  faPlaneArrival,
  faPlaneDeparture,
  faPlaneUp,
  faPlantWilt,
  faPlug,
  faPlus,
  faPrescriptionBottle,
  faPrint,
  faPuzzlePiece,
  faQrcode,
  faQuestion,
  faQuoteLeft,
  faQuoteRight,
  faRadio,
  faRainbow,
  faReceipt,
  faRecordVinyl,
  faRibbon,
  faRoad,
  faRocket,
  faRoute,
  faSackDollar,
  faSailboat,
  faSatellite,
  faSatelliteDish,
  faScaleBalanced,
  faSchool,
  faScissors,
  faScrewdriverWrench,
  faScroll,
  faSeedling,
  faServer,
  faShapes,
  faShield,
  faShieldHalved,
  faShip,
  faShoePrints,
  faShop,
  faShoppingBag,
  faShower,
  faShrimp,
  faSign,
  faSignal,
  faSignature,
  faSignHanging,
  faSkull,
  faSkullCrossbones,
  faSmog,
  faSnowflake,
  faSoap,
  faSoccerBall,
  faSpa,
  faSpider,
  faSprayCan,
  faSquare,
  faStamp,
  faStar,
  faStarAndCrescent,
  faStarOfDavid,
  faStarOfLife,
  faStethoscope,
  faStopwatch,
  faStore,
  faSubway,
  faSuitcase,
  faSuitcaseRolling,
  faSun,
  faSyringe,
  faTableTennisPaddleBall,
  faTape,
  faTaxi,
  faTeeth,
  faTemperatureHalf,
  faTemperatureHigh,
  faTemperatureLow,
  faTent,
  faTerminal,
  faThermometer,
  faThumbsDown,
  faThumbsUp,
  faTicket,
  faTools,
  faTooth,
  faToriiGate,
  faTornado,
  faTowerBroadcast,
  faTowerCell,
  faTowerObservation,
  faTractor,
  faTrafficLight,
  faTrain,
  faTrainSubway,
  faTram,
  faTree,
  faTriangleExclamation,
  faTrophy,
  faTruck,
  faTruckFast,
  faUmbrella,
  faUmbrellaBeach,
  faUniversity,
  faUnlock,
  faUser,
  faUserAstronaut,
  faUserCheck,
  faUserClock,
  faUserDoctor,
  faUserFriends,
  faUserGear,
  faUserGraduate,
  faUserGroup,
  faUserMinus,
  faUserNinja,
  faUserNurse,
  faUserPen,
  faUserPlus,
  faUsers,
  faUserSecret,
  faUserShield,
  faUserTie,
  faUserXmark,
  faUtensils,
  faVanShuttle,
  faVault,
  faVial,
  faVideo,
  faVihara,
  faVolcano,
  faVolleyball,
  faWallet,
  faWandMagic,
  faWandMagicSparkles,
  faWarehouse,
  faWater,
  faWaterLadder,
  faWeightScale,
  faWheatAwn,
  faWhiskeyGlass,
  faWifi,
  faWind,
  faWineBottle,
  faWineGlass,
  faWorm,
  faXmark,
  faYinYang,
  type IconDefinition,
} from '@fortawesome/free-solid-svg-icons'

export const PROJECT_ICON_REGISTRY: Record<string, IconDefinition> = {
  "folder": faFolder,
  "folder-open": faFolderOpen,
  "brain": faBrain,
  "heart": faHeart,
  "sack-dollar": faSackDollar,
  "dumbbell": faDumbbell,
  "briefcase": faBriefcase,
  "suitcase": faSuitcase,
  "bag-shopping": faBagShopping,
  "shopping-bag": faShoppingBag,
  "cart-shopping": faCartShopping,
  "store": faStore,
  "warehouse": faWarehouse,
  "industry": faIndustry,
  "building": faBuilding,
  "house": faHouse,
  "house-chimney": faHouseChimney,
  "school": faSchool,
  "hospital": faHospital,
  "landmark": faLandmark,
  "hotel": faHotel,
  "university": faUniversity,
  "shop": faShop,
  "gear": faGear,
  "gears": faGears,
  "screwdriver-wrench": faScrewdriverWrench,
  "hammer": faHammer,
  "code": faCode,
  "laptop": faLaptop,
  "laptop-code": faLaptopCode,
  "computer": faComputer,
  "desktop": faDesktop,
  "server": faServer,
  "database": faDatabase,
  "network-wired": faNetworkWired,
  "microchip": faMicrochip,
  "plug": faPlug,
  "keyboard": faKeyboard,
  "mouse": faMouse,
  "print": faPrint,
  "camera": faCamera,
  "video": faVideo,
  "film": faFilm,
  "clapperboard": faClapperboard,
  "headphones": faHeadphones,
  "headset": faHeadset,
  "microphone": faMicrophone,
  "microscope": faMicroscope,
  "flask": faFlask,
  "vial": faVial,
  "atom": faAtom,
  "magnifying-glass": faMagnifyingGlass,
  "bug": faBug,
  "terminal": faTerminal,
  "cube": faCube,
  "cubes": faCubes,
  "shapes": faShapes,
  "square": faSquare,
  "qrcode": faQrcode,
  "barcode": faBarcode,
  "fingerprint": faFingerprint,
  "key": faKey,
  "lock": faLock,
  "lock-open": faLockOpen,
  "unlock": faUnlock,
  "shield": faShield,
  "shield-halved": faShieldHalved,
  "tools": faTools,
  "dollar-sign": faDollarSign,
  "money-bill": faMoneyBill,
  "money-bill-wave": faMoneyBillWave,
  "wallet": faWallet,
  "credit-card": faCreditCard,
  "coins": faCoins,
  "money-check": faMoneyCheck,
  "hand-holding-dollar": faHandHoldingDollar,
  "chart-line": faChartLine,
  "chart-area": faChartArea,
  "chart-bar": faChartBar,
  "chart-column": faChartColumn,
  "chart-pie": faChartPie,
  "percent": faPercent,
  "calculator": faCalculator,
  "receipt": faReceipt,
  "cash-register": faCashRegister,
  "vault": faVault,
  "piggy-bank": faPiggyBank,
  "bitcoin-sign": faBitcoinSign,
  "tree": faTree,
  "leaf": faLeaf,
  "seedling": faSeedling,
  "clover": faClover,
  "plant-wilt": faPlantWilt,
  "spa": faSpa,
  "sun": faSun,
  "moon": faMoon,
  "cloud": faCloud,
  "rainbow": faRainbow,
  "snowflake": faSnowflake,
  "bolt": faBolt,
  "fire": faFire,
  "water": faWater,
  "mountain": faMountain,
  "volcano": faVolcano,
  "wind": faWind,
  "globe": faGlobe,
  "earth-americas": faEarthAmericas,
  "earth-africa": faEarthAfrica,
  "earth-asia": faEarthAsia,
  "earth-europe": faEarthEurope,
  "earth-oceania": faEarthOceania,
  "map": faMap,
  "location-dot": faLocationDot,
  "compass": faCompass,
  "route": faRoute,
  "tent": faTent,
  "campground": faCampground,
  "umbrella": faUmbrella,
  "feather": faFeather,
  "tornado": faTornado,
  "smog": faSmog,
  "mountain-sun": faMountainSun,
  "cat": faCat,
  "dog": faDog,
  "cow": faCow,
  "horse": faHorse,
  "frog": faFrog,
  "fish": faFish,
  "crow": faCrow,
  "dove": faDove,
  "kiwi-bird": faKiwiBird,
  "spider": faSpider,
  "hippo": faHippo,
  "worm": faWorm,
  "shrimp": faShrimp,
  "paw": faPaw,
  "horse-head": faHorseHead,
  "otter": faOtter,
  "apple-whole": faAppleWhole,
  "lemon": faLemon,
  "egg": faEgg,
  "cheese": faCheese,
  "bread-slice": faBreadSlice,
  "cookie": faCookie,
  "cookie-bite": faCookieBite,
  "ice-cream": faIceCream,
  "bowl-food": faBowlFood,
  "bowl-rice": faBowlRice,
  "mug-hot": faMugHot,
  "mug-saucer": faMugSaucer,
  "wine-glass": faWineGlass,
  "beer-mug-empty": faBeerMugEmpty,
  "glass-water": faGlassWater,
  "utensils": faUtensils,
  "pizza-slice": faPizzaSlice,
  "drumstick-bite": faDrumstickBite,
  "bottle-water": faBottleWater,
  "carrot": faCarrot,
  "wheat-awn": faWheatAwn,
  "burger": faBurger,
  "hotdog": faHotdog,
  "pepper-hot": faPepperHot,
  "jar": faJar,
  "wine-bottle": faWineBottle,
  "champagne-glasses": faChampagneGlasses,
  "whiskey-glass": faWhiskeyGlass,
  "martini-glass": faMartiniGlass,
  "glass-cheers": faGlassCheers,
  "glass-martini": faGlassMartini,
  "futbol": faFutbol,
  "soccer-ball": faSoccerBall,
  "football": faFootball,
  "basketball": faBasketball,
  "baseball": faBaseball,
  "volleyball": faVolleyball,
  "hockey-puck": faHockeyPuck,
  "table-tennis-paddle-ball": faTableTennisPaddleBall,
  "gamepad": faGamepad,
  "trophy": faTrophy,
  "medal": faMedal,
  "award": faAward,
  "ribbon": faRibbon,
  "stopwatch": faStopwatch,
  "shoe-prints": faShoePrints,
  "helmet-safety": faHelmetSafety,
  "person-swimming": faPersonSwimming,
  "person-running": faPersonRunning,
  "person-biking": faPersonBiking,
  "person-skiing": faPersonSkiing,
  "person-snowboarding": faPersonSnowboarding,
  "person-skating": faPersonSkating,
  "person-walking": faPersonWalking,
  "person-hiking": faPersonHiking,
  "bowling-ball": faBowlingBall,
  "bullseye": faBullseye,
  "chess": faChess,
  "puzzle-piece": faPuzzlePiece,
  "dice": faDice,
  "hand-fist": faHandFist,
  "hand": faHand,
  "handshake": faHandshake,
  "thumbs-up": faThumbsUp,
  "thumbs-down": faThumbsDown,
  "plane": faPlane,
  "plane-up": faPlaneUp,
  "plane-departure": faPlaneDeparture,
  "plane-arrival": faPlaneArrival,
  "helicopter": faHelicopter,
  "rocket": faRocket,
  "ship": faShip,
  "ferry": faFerry,
  "sailboat": faSailboat,
  "anchor": faAnchor,
  "truck": faTruck,
  "truck-fast": faTruckFast,
  "tractor": faTractor,
  "motorcycle": faMotorcycle,
  "bicycle": faBicycle,
  "car": faCar,
  "car-side": faCarSide,
  "bus": faBus,
  "bus-simple": faBusSimple,
  "train": faTrain,
  "train-subway": faTrainSubway,
  "tram": faTram,
  "subway": faSubway,
  "taxi": faTaxi,
  "ambulance": faAmbulance,
  "van-shuttle": faVanShuttle,
  "traffic-light": faTrafficLight,
  "road": faRoad,
  "sign": faSign,
  "sign-hanging": faSignHanging,
  "tower-observation": faTowerObservation,
  "tower-cell": faTowerCell,
  "tower-broadcast": faTowerBroadcast,
  "satellite": faSatellite,
  "gas-pump": faGasPump,
  "charging-station": faChargingStation,
  "map-location-dot": faMapLocationDot,
  "location-crosshairs": faLocationCrosshairs,
  "compass-drafting": faCompassDrafting,
  "caravan": faCaravan,
  "flag": faFlag,
  "flag-checkered": faFlagCheckered,
  "passport": faPassport,
  "ticket": faTicket,
  "suitcase-rolling": faSuitcaseRolling,
  "luggage-cart": faLuggageCart,
  "concierge-bell": faConciergeBell,
  "umbrella-beach": faUmbrellaBeach,
  "bridge": faBridge,
  "user": faUser,
  "users": faUsers,
  "user-group": faUserGroup,
  "user-friends": faUserFriends,
  "people-group": faPeopleGroup,
  "people-line": faPeopleLine,
  "user-tie": faUserTie,
  "user-ninja": faUserNinja,
  "user-secret": faUserSecret,
  "user-astronaut": faUserAstronaut,
  "user-graduate": faUserGraduate,
  "user-shield": faUserShield,
  "user-clock": faUserClock,
  "user-gear": faUserGear,
  "user-pen": faUserPen,
  "user-plus": faUserPlus,
  "user-minus": faUserMinus,
  "user-xmark": faUserXmark,
  "user-check": faUserCheck,
  "user-doctor": faUserDoctor,
  "user-nurse": faUserNurse,
  "baby": faBaby,
  "child": faChild,
  "person": faPerson,
  "person-dress": faPersonDress,
  "person-praying": faPersonPraying,
  "person-pregnant": faPersonPregnant,
  "heart-pulse": faHeartPulse,
  "heart-crack": faHeartCrack,
  "tooth": faTooth,
  "teeth": faTeeth,
  "bone": faBone,
  "eye": faEye,
  "ear-listen": faEarListen,
  "hands": faHands,
  "hands-praying": faHandsPraying,
  "hand-holding-heart": faHandHoldingHeart,
  "hand-holding-medical": faHandHoldingMedical,
  "hand-back-fist": faHandBackFist,
  "kit-medical": faKitMedical,
  "stethoscope": faStethoscope,
  "syringe": faSyringe,
  "flask-vial": faFlaskVial,
  "prescription-bottle": faPrescriptionBottle,
  "bandage": faBandage,
  "capsules": faCapsules,
  "pills": faPills,
  "thermometer": faThermometer,
  "temperature-high": faTemperatureHigh,
  "temperature-low": faTemperatureLow,
  "temperature-half": faTemperatureHalf,
  "weight-scale": faWeightScale,
  "scale-balanced": faScaleBalanced,
  "bath": faBath,
  "shower": faShower,
  "soap": faSoap,
  "water-ladder": faWaterLadder,
  "hot-tub-person": faHotTubPerson,
  "star": faStar,
  "star-and-crescent": faStarAndCrescent,
  "star-of-david": faStarOfDavid,
  "star-of-life": faStarOfLife,
  "crown": faCrown,
  "burst": faBurst,
  "bomb": faBomb,
  "ghost": faGhost,
  "skull": faSkull,
  "skull-crossbones": faSkullCrossbones,
  "mask": faMask,
  "wand-magic": faWandMagic,
  "wand-magic-sparkles": faWandMagicSparkles,
  "hamsa": faHamsa,
  "khanda": faKhanda,
  "yin-yang": faYinYang,
  "torii-gate": faToriiGate,
  "vihara": faVihara,
  "cross": faCross,
  "dharmachakra": faDharmachakra,
  "place-of-worship": faPlaceOfWorship,
  "feather-pointed": faFeatherPointed,
  "circle-check": faCircleCheck,
  "circle-info": faCircleInfo,
  "circle-question": faCircleQuestion,
  "circle-plus": faCirclePlus,
  "circle-minus": faCircleMinus,
  "circle-xmark": faCircleXmark,
  "circle-half-stroke": faCircleHalfStroke,
  "question": faQuestion,
  "plus": faPlus,
  "minus": faMinus,
  "xmark": faXmark,
  "ban": faBan,
  "check": faCheck,
  "triangle-exclamation": faTriangleExclamation,
  "bookmark": faBookmark,
  "lightbulb": faLightbulb,
  "bell": faBell,
  "bell-slash": faBellSlash,
  "bullhorn": faBullhorn,
  "comment": faComment,
  "comments": faComments,
  "envelope": faEnvelope,
  "envelope-open": faEnvelopeOpen,
  "paper-plane": faPaperPlane,
  "paperclip": faPaperclip,
  "link": faLink,
  "link-slash": faLinkSlash,
  "signature": faSignature,
  "quote-left": faQuoteLeft,
  "quote-right": faQuoteRight,
  "asterisk": faAsterisk,
  "certificate": faCertificate,
  "gem": faGem,
  "diamond": faDiamond,
  "diamond-turn-right": faDiamondTurnRight,
  "hat-wizard": faHatWizard,
  "hat-cowboy": faHatCowboy,
  "hat-cowboy-side": faHatCowboySide,
  "magnifying-glass-plus": faMagnifyingGlassPlus,
  "magnifying-glass-minus": faMagnifyingGlassMinus,
  "magnifying-glass-chart": faMagnifyingGlassChart,
  "satellite-dish": faSatelliteDish,
  "radio": faRadio,
  "signal": faSignal,
  "wifi": faWifi,
  "mobile": faMobile,
  "mobile-screen": faMobileScreen,
  "phone": faPhone,
  "phone-volume": faPhoneVolume,
  "door-open": faDoorOpen,
  "door-closed": faDoorClosed,
  "hourglass": faHourglass,
  "hourglass-half": faHourglassHalf,
  "clock": faClock,
  "clock-rotate-left": faClockRotateLeft,
  "alarm-clock": faAlarmClock,
  "calendar": faCalendar,
  "calendar-check": faCalendarCheck,
  "calendar-days": faCalendarDays,
  "calendar-plus": faCalendarPlus,
  "calendar-xmark": faCalendarXmark,
  "note-sticky": faNoteSticky,
  "file": faFile,
  "file-lines": faFileLines,
  "file-code": faFileCode,
  "file-csv": faFileCsv,
  "file-pdf": faFilePdf,
  "file-word": faFileWord,
  "file-excel": faFileExcel,
  "file-zipper": faFileZipper,
  "file-audio": faFileAudio,
  "file-video": faFileVideo,
  "file-medical": faFileMedical,
  "file-prescription": faFilePrescription,
  "file-contract": faFileContract,
  "file-signature": faFileSignature,
  "folder-tree": faFolderTree,
  "folder-plus": faFolderPlus,
  "folder-minus": faFolderMinus,
  "folder-closed": faFolderClosed,
  "copy": faCopy,
  "paste": faPaste,
  "scissors": faScissors,
  "pen": faPen,
  "pen-fancy": faPenFancy,
  "pen-nib": faPenNib,
  "pencil": faPencil,
  "paintbrush": faPaintbrush,
  "palette": faPalette,
  "brush": faBrush,
  "fill-drip": faFillDrip,
  "broom": faBroom,
  "spray-can": faSprayCan,
  "stamp": faStamp,
  "book": faBook,
  "book-open": faBookOpen,
  "book-bookmark": faBookBookmark,
  "book-open-reader": faBookOpenReader,
  "newspaper": faNewspaper,
  "scroll": faScroll,
  "clipboard": faClipboard,
  "clipboard-check": faClipboardCheck,
  "clipboard-list": faClipboardList,
  "archive": faArchive,
  "box": faBox,
  "box-open": faBoxOpen,
  "boxes-stacked": faBoxesStacked,
  "gift": faGift,
  "gifts": faGifts,
  "cake": faCake,
  "cake-candles": faCakeCandles,
  "music": faMusic,
  "guitar": faGuitar,
  "drum": faDrum,
  "compact-disc": faCompactDisc,
  "record-vinyl": faRecordVinyl,
  "tape": faTape,
  "microphone-lines": faMicrophoneLines,
  "masks-theater": faMasksTheater,
}
